name: 'POC of release'
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Configure Git User"
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: "Prepare release"
        run: |
          NEXT_RELEASE=$(grep 'version: ' properties.yml | sed 's/version: //' | xargs)
          echo "$NEXT_RELEASE"
          echo "NEXT_RELEASE=$NEXT_RELEASE" >> $GITHUB_ENV
